In [3]:
import numpy as np

In [13]:
A = np.array([[1, 1, 1], [0.05, 0.07, 0], [0.05, 0, 0.06]])
B = np.array([50000, 2250, 1400])

X = np.linalg.solve(A, B).astype('int')

print(f"Кількість грошей, які вкладник поклав на перший, другий та третій рахунок: {X}")

Кількість грошей, які вкладник поклав на перший, другий та третій рахунок: [10000 25000 15000]


In [16]:
A = np.array([[0,2,1], [2,1,0], [1,1,1]])
B = np.array([1448, 1428, 1328])

X = np.linalg.solve(A,B).astype('int')

print(f"Кількість телефонів кожної моделі: {X}")

Кількість телефонів кожної моделі: [436 556 336]


In [28]:
a = np.matrix("3,0,3;6,0.25,0;1,0.33,1")
b = np.matrix("1;1;1")
a_solve = np.linalg.solve(a,b)
a_solve

matrix([[0.08249158],
        [2.02020202],
        [0.25084175]])

In [29]:
a = round(a_solve[0, 0], 1)
b = round(a_solve[1, 0], 1)
c = round(a_solve[2, 0], 1)
a, b ,c

(0.1, 2.0, 0.3)

In [31]:
def get_result(n):
    result = 1 / n
    result = round(result, 1)
    return result

In [32]:
a = get_result(a)
b = get_result(b)
c = get_result(c)
a, b, c

(10.0, 0.5, 3.3)

In [33]:
a = np.matrix("1,1,1;9,3,1;1,-1,1")
b = np.matrix("12;54;2")
a_solve = np.linalg.solve(a,b)
result = a_solve.astype('int')
result

matrix([[4],
        [5],
        [3]])

In [34]:
def get_polynom(coords):
    a = []
    b = []
    for x, y in coords:
        row = []
        b.append(y)
        for i in range(len(coords)):
            row.append(x ** i)
        a.append(row)
    return np.linalg.solve(a, b).astype('int')

get_polynom([(1,2), (3,4)])

array([1, 1])